--/* Showing results for Users.xlsx */
--
--/* CREATE TABLE */
--CREATE TABLE table_name(
--id DOUBLE,
--username DOUBLE,
--first_name VARCHAR(100),
--last_name VARCHAR(100),
--email VARCHAR(100),
--gender VARCHAR(100),
--password VARCHAR(100)
--);
--
--/* UPDATE QUERY NO: 1 */
--UPDATE
--table_name
--SET
--id = 1,
--username = 1,
--first_name = 'Nonie',
--last_name = 'Poyntz',
--email = 'npoyntz0@baidu.com',
--gender = 'Agender',
--password = 'password'
--WHERE
--id = 1;
--
--/* UPDATE QUERY NO: 2 */
--UPDATE
--table_name
--SET
--id = 2,
--username = 2,
--first_name = 'Kizzie',
--last_name = 'Wingfield',
--email = 'kwingfield1@cornell.edu',
--gender = 'Agender',
--password = 'password'
--WHERE
--id = 2;
--
--/* UPDATE QUERY NO: 3 */
--UPDATE
--table_name
--SET
--id = 3,
--username = 3,
--first_name = 'Rudd',
--last_name = 'Brehault',
--email = 'rbrehault2@live.com',
--gender = 'Non-binary',
--password = 'password'
--WHERE
--id = 3;
--
--/* UPDATE QUERY NO: 4 */
--UPDATE
--table_name
--SET
--id = 4,
--username = 4,
--first_name = 'Wiatt',
--last_name = 'Elphinstone',
--email = 'welphinstone3@europa.eu',
--gender = 'Genderfluid',
--password = 'password'
--WHERE
--id = 4;
--
--/* UPDATE QUERY NO: 5 */
--UPDATE
--table_name
--SET
--id = 5,
--username = 5,
--first_name = 'Amabel',
--last_name = 'Pattington',
--email = 'apattington4@mapquest.com',
--gender = 'Agender',
--password = 'password'
--WHERE
--id = 5;
--
--/* UPDATE QUERY NO: 6 */
--UPDATE
--table_name
--SET
--id = 6,
--username = 6,
--first_name = 'Bennie',
--last_name = 'Adriaan',
--email = 'badriaan5@ocn.ne.jp',
--gender = 'Bigender',
--password = 'password'
--WHERE
--id = 6;
--
--/* UPDATE QUERY NO: 7 */
--UPDATE
--table_name
--SET
--id = 7,
--username = 7,
--first_name = 'Aguistin',
--last_name = 'Wallbrook',
--email = 'awallbrook6@blogs.com',
--gender = 'Male',
--password = 'password'
--WHERE
--id = 7;
--
--/* UPDATE QUERY NO: 8 */
--UPDATE
--table_name
--SET
--id = 8,
--username = 8,
--first_name = 'Lenna',
--last_name = 'Stickells',
--email = 'lstickells7@google.com.au',
--gender = 'Agender',
--password = 'password'
--WHERE
--id = 8;
--
--/* UPDATE QUERY NO: 9 */
--UPDATE
--table_name
--SET
--id = 9,
--username = 9,
--first_name = 'Jere',
--last_name = 'Keeri',
--email = 'jkeeri8@walmart.com',
--gender = 'Agender',
--password = 'password'
--WHERE
--id = 9;
--
--/* UPDATE QUERY NO: 10 */
--UPDATE
--table_name
--SET
--id = 10,
--username = 10,
--first_name = 'Alayne',
--last_name = 'Crellim',
--email = 'acrellim9@mashable.com',
--gender = 'Non-binary',
--password = 'password'
--WHERE
--id = 10;
--
--/* UPDATE QUERY NO: 11 */
--UPDATE
--table_name
--SET
--id = 11,
--username = 11,
--first_name = 'Tine',
--last_name = 'Bunn',
--email = 'tbunna@t-online.de',
--gender = 'Male',
--password = 'password'
--WHERE
--id = 11;
--
--/* UPDATE QUERY NO: 12 */
--UPDATE
--table_name
--SET
--id = 12,
--username = 12,
--first_name = 'Spencer',
--last_name = 'Lindermann',
--email = 'slindermannb@redcross.org',
--gender = 'Polygender',
--password = 'password'
--WHERE
--id = 12;
--
--/* UPDATE QUERY NO: 13 */
--UPDATE
--table_name
--SET
--id = 13,
--username = 13,
--first_name = 'Pearce',
--last_name = 'Este',
--email = 'pestec@mtv.com',
--gender = 'Genderqueer',
--password = 'password'
--WHERE
--id = 13;
--
--/* UPDATE QUERY NO: 14 */
--UPDATE
--table_name
--SET
--id = 14,
--username = 14,
--first_name = 'Garrek',
--last_name = 'Rainard',
--email = 'grainardd@sbwire.com',
--gender = 'Female',
--password = 'password'
--WHERE
--id = 14;
--
--/* UPDATE QUERY NO: 15 */
--UPDATE
--table_name
--SET
--id = 15,
--username = 15,
--first_name = 'Elyse',
--last_name = 'Haszard',
--email = 'ehaszarde@bbb.org',
--gender = 'Female',
--password = 'password'
--WHERE
--id = 15;
--
--/* UPDATE QUERY NO: 16 */
--UPDATE
--table_name
--SET
--id = 16,
--username = 16,
--first_name = 'Daniel',
--last_name = 'Rummery',
--email = 'drummeryf@columbia.edu',
--gender = 'Agender',
--password = 'password'
--WHERE
--id = 16;
--
--/* UPDATE QUERY NO: 17 */
--UPDATE
--table_name
--SET
--id = 17,
--username = 17,
--first_name = 'Joanna',
--last_name = 'Ridulfo',
--email = 'jridulfog@slideshare.net',
--gender = 'Agender',
--password = 'password'
--WHERE
--id = 17;
--
--/* UPDATE QUERY NO: 18 */
--UPDATE
--table_name
--SET
--id = 18,
--username = 18,
--first_name = 'Jessalyn',
--last_name = 'Eliasen',
--email = 'jeliasenh@slate.com',
--gender = 'Non-binary',
--password = 'password'
--WHERE
--id = 18;
--
--/* UPDATE QUERY NO: 19 */
--UPDATE
--table_name
--SET
--id = 19,
--username = 19,
--first_name = 'Trula',
--last_name = 'Crust',
--email = 'tcrusti@omniture.com',
--gender = 'Genderqueer',
--password = 'password'
--WHERE
--id = 19;
--
--/* UPDATE QUERY NO: 20 */
--UPDATE
--table_name
--SET
--id = 20,
--username = 20,
--first_name = 'Lurline',
--last_name = 'Sarjant',
--email = 'lsarjantj@oakley.com',
--gender = 'Female',
--password = 'password'
--WHERE
--id = 20;
